version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel
    volumes:
      - .:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-laravel
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
